# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Apel unit testing integration test

on: [push, pull_request]

jobs:
  apel-unit-test:
    name: "Apel unit test using MariaDB: ${{ matrix.mariadb-version }} Python:${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mariadb-version: ["10.3"]
        python-version: ["2.7"] #, "3.6"]

    services:
      mariadb:
        image: "mariadb:${{ matrix.mariadb-version }}"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: "apel_unittest"
          MYSQL_USER: "root"
          MYSQL_PASSWORD: ""

        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        ports: ["3306:3306"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test MariaDB connection
      run: sudo mysql --user root --host '172.18.0.1' <<< 'show databases;'

    - name: Display info
      run: |
        echo ${{ runner.os }}
        echo ${{ steps.get-date.outputs.date }}

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # - uses: actions/cache@v2
    #   path: /var/lib/docker
    #   key: ${{ runner.os }}-docker-${{ steps.get-date.outputs.date }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: .github/actions/install_dependencies.sh

    - name: Unittest with Coverage
      run: .github/actions/run_tests.sh

    #- name: Coverage test with Codecov
    #  run: codecov
